services:
  app:
    build: .
    ports:
      - "8082:8082"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://interchange.proxy.rlwy.net:56516/railw?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      JAVA_TOOL_OPTIONS: -Djdk.tls.client.protocols=TLSv1.2

    networks:
      - ecoride-network

networks:
  ecoride-network:
    driver: bridge
